// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Bool = 2,
  String = 3,
  Number = 4,
  Null = 5,
  Name = 6,
  InfixExpr = 7,
  OpMul = 8,
  OpDiv = 9,
  OpSub = 10,
  OpAdd = 11
